# Generated by Django 6.0.2 on 2026-02-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Аббревиатура'),
        ),
        migrations.AddField(
            model_name='campus',
            name='metro_station',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Станция метро'),
        ),
    ]
