# Generated by Django 6.0.2 on 2026-02-22 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='course_years',
        ),
        migrations.RemoveField(
            model_name='project',
            name='filters',
        ),
        migrations.RemoveField(
            model_name='project',
            name='schedules',
        ),
        migrations.AddField(
            model_name='filtercategory',
            name='type',
            field=models.CharField(choices=[('theme', 'Тематика'), ('specialty', 'Специальность'), ('course', 'Курс'), ('campus', 'Корпус'), ('difficulty', 'Сложность'), ('partner', 'Партнёр')], max_length=20, null=True, unique=True, verbose_name='Тип категории'),
        ),
        migrations.AddField(
            model_name='project',
            name='courses',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category__type': 'course'}, related_name='projects_as_course', to='showcase.filteroption', verbose_name='Курсы студентов'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
        migrations.AddField(
            model_name='project',
            name='specialties',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category__type': 'specialty'}, related_name='projects_as_specialty', to='showcase.filteroption', verbose_name='Специальности'),
        ),
        migrations.AddField(
            model_name='project',
            name='theme',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__type': 'theme'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_theme', to='showcase.filteroption', verbose_name='Тематика'),
        ),
        migrations.AlterField(
            model_name='filtercategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='project',
            name='campus',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__type': 'campus'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_campus', to='showcase.filteroption', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='project',
            name='difficulty',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__type': 'difficulty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_difficulty', to='showcase.filteroption', verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='project',
            name='internship',
            field=models.BooleanField(default=False, verbose_name='Стажировка'),
        ),
    ]
