# Generated by Django 6.0.2 on 2026-03-15 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_project_shedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='campus',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__category_type': 'campus'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_campus', to='showcase.campus', verbose_name='Корпус'),
        ),
    ]
